source 'https://rubygems.org'

gem 'rails', '4.0.1'

gem 'sqlite3'

gem 'authorized_rails_scaffolds'
gem 'awesome_nested_set'
gem 'cancan'
gem 'ckeditor'
gem 'ckeditor_rails'
gem 'devise'
gem 'dragonfly'
gem 'enumerize'
gem 'livequery-rails'
gem 'slim'
gem 'slim-rails'
gem 'simple_form'
gem 'simple-navigation'
gem 'simple_navigation_renderers'
gem 'stringex'
gem 'the_sortable_tree'
gem 'paper_trail', '>= 3.0.0rc2'
gem 'pry-rails'

gem 'sass-rails', '~> 4.0.0'
gem 'less-rails'
gem 'uglifier', '>= 1.3.0'
gem 'coffee-rails', '~> 4.0.0'
gem 'therubyracer', platforms: :ruby
gem 'jquery-rails'
gem 'jquery-ui-rails'
gem 'twitter-bootstrap-rails'
